[supervisord]
nodaemon=true
logfile=/tmp/supervisor/supervisord.log
pidfile=/tmp/supervisor/supervisord.pid

[program:php]
command=php-fpm --nodaemonize
user=sail
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0