worker_processes 1;
events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name _;
        client_max_body_size 100M;

        # Serve Vue frontend
        location / {
            root /var/www/vue;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Proxy API requests to Laravel backend
        location ^~ /api/ {
#            proxy_pass http://backend:80;
#            proxy_http_version 1.1;
#            proxy_set_header Host $host;
#            proxy_set_header X-Real-IP $remote_addr;
#            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#            proxy_set_header X-Forwarded-Proto $scheme;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_pass backend:9000;
            fastcgi_read_timeout 300s;
        }

        location = /api {
            return 301 /api/;
        }

        location /storage/ {
            alias /var/www/html/storage/app/public/;
            expires max;
            add_header Cache-Control "public, max-age=31536000";
        }

        # Optional: Proxy other Laravel routes (e.g., /sanctum, /login)
        location /sanctum/ {
            proxy_pass http://backend:80;
        }
    }
}